# Generated by Django 5.0.1 on 2026-05-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('negocios', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duracion_minutos', models.IntegerField(help_text='Se copia del servicio al crear la cita', verbose_name='Duración (minutos)')),
                ('estado', models.CharField(choices=[('pendiente_abono', 'Pendiente de abono'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='pendiente_abono', max_length=20, verbose_name='Estado')),
                ('origen', models.CharField(choices=[('web', 'Reserva Web'), ('manual', 'Registro Manual'), ('walk_in', 'Sin reserva previa')], default='web', max_length=20, verbose_name='Origen')),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('fecha_limite_abono', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite de abono')),
                ('confirmada_por_admin', models.BooleanField(default=False, verbose_name='Confirmada por admin')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio enviado')),
                ('confirmacion_enviada', models.BooleanField(default=False, verbose_name='Confirmación enviada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clientes.cliente', verbose_name='Cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='negocios.negocio', verbose_name='Negocio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='citas_cita_fecha_h_fd1701_idx'), models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx'), models.Index(fields=['negocio', 'fecha_hora'], name='citas_cita_negocio_76b56e_idx')],
            },
        ),
    ]
