# Generated by Django 5.0.1 on 2026-06-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('clientes', '0003_cliente_ciudad_cliente_codigo_postal_and_more'),
        ('negocios', '0003_negocio_es_a_domicilio'),
        ('servicios', '0002_servicio_requiere_contacto_directo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['negocio', 'estado', 'fecha_hora'], name='citas_cita_negocio_e19197_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['cliente', '-fecha_hora'], name='citas_cita_cliente_86e5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['negocio', 'cliente', 'fecha_hora', 'estado'], name='citas_cita_negocio_bcaaf5_idx'),
        ),
    ]
