# Generated by Django 5.0.1 on 2026-10-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_citas_cita_negocio_e19197_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='recordatorio_2h_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio 2 h enviado'),
        ),
    ]
