# Generated by Django 5.0.1 on 2026-05-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion_cita', 'Confirmación de cita'), ('recordatorio_cita', 'Recordatorio de cita'), ('recordatorio_abono', 'Recordatorio de abono'), ('confirmacion_abono', 'Confirmación de abono'), ('cancelacion', 'Cancelación'), ('promocion', 'Promoción'), ('sugerencia_cita', 'Sugerencia de próxima cita'), ('reactivacion', 'Reactivación de cliente')], max_length=30, verbose_name='Tipo')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=20, verbose_name='Canal')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('asunto', models.CharField(blank=True, max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('id_externo', models.CharField(blank=True, help_text='ID de Twilio, etc.', max_length=200, verbose_name='ID externo')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha programada')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='citas.cita', verbose_name='Cita relacionada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='notificacio_estado_52a925_idx'), models.Index(fields=['tipo'], name='notificacio_tipo_2df5d5_idx'), models.Index(fields=['fecha_programada'], name='notificacio_fecha_p_42e0e6_idx')],
            },
        ),
    ]
