# Generated by Django 5.0.1 on 2026-06-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('push', 'Push Notification'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], max_length=20, verbose_name='Canal'),
        ),
    ]
