# Generated by Django 5.0.1 on 2026-08-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_clientes_cl_negocio_dcd8fa_idx_and_more'),
        ('notificaciones', '0002_alter_notificacion_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='Endpoint')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256dh')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Suscripción Push de Cliente',
                'verbose_name_plural': 'Suscripciones Push de Clientes',
                'ordering': ['-fecha_suscripcion'],
                'indexes': [models.Index(fields=['cliente', 'activa'], name='notificacio_cliente_ffc93e_idx'), models.Index(fields=['endpoint'], name='notificacio_endpoin_ffc295_idx')],
            },
        ),
    ]
