# Generated by Django 5.0.1 on 2026-08-26 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_onboardingprogress'),
        ('notificaciones', '0003_clientepushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='Endpoint')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256dh')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('negocio', models.ForeignKey(help_text='Negocio al que pertenece este usuario', on_delete=django.db.models.deletion.CASCADE, related_name='admin_push_subscriptions', to='negocios.negocio', verbose_name='Negocio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción Push de Usuario Admin',
                'verbose_name_plural': 'Suscripciones Push de Usuarios Admin',
                'ordering': ['-fecha_suscripcion'],
                'indexes': [models.Index(fields=['user', 'activa'], name='notificacio_user_id_c5c4e2_idx'), models.Index(fields=['negocio', 'activa'], name='notificacio_negocio_750969_idx'), models.Index(fields=['endpoint'], name='notificacio_endpoin_7ea22b_idx')],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
