# Generated by Django 5.0.1 on 2026-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_usuariopushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('confirmacion_cita', 'Confirmación de cita'), ('recordatorio_cita', 'Recordatorio de cita'), ('recordatorio_abono', 'Recordatorio de abono'), ('confirmacion_abono', 'Confirmación de abono'), ('cancelacion', 'Cancelación'), ('abono_rechazado', 'Abono rechazado'), ('promocion', 'Promoción'), ('sugerencia_cita', 'Sugerencia de próxima cita'), ('reactivacion', 'Reactivación de cliente')], max_length=30, verbose_name='Tipo'),
        ),
    ]
