# Generated by Django 5.0.1 on 2026-10-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_citas_cita_negocio_e19197_idx_and_more'),
        ('negocios', '0005_medios_de_pago'),
        ('notificaciones', '0005_tipo_abono_rechazado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita_nueva', 'Nueva cita'), ('abono', 'Abono'), ('cita_modificada', 'Cita modificada por el cliente'), ('cita_cancelada', 'Cita cancelada por el cliente')], max_length=20, verbose_name='Tipo')),
                ('detalle', models.CharField(blank=True, max_length=200, verbose_name='Detalle')),
                ('resuelto', models.BooleanField(db_index=True, default=False, verbose_name='Resuelto')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado')),
                ('resuelto_en', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto en')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='citas.cita', verbose_name='Cita')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Pendiente',
                'verbose_name_plural': 'Pendientes',
                'ordering': ['-actualizado_en'],
                'indexes': [models.Index(fields=['negocio', 'resuelto', '-actualizado_en'], name='notificacio_negocio_31deed_idx')],
            },
        ),
    ]
