# Generated by Django 5.0.1 on 2026-10-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0007_recordatorio_2h'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepushsubscription',
            name='fallos_consecutivos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fallos seguidos'),
        ),
        migrations.AddField(
            model_name='usuariopushsubscription',
            name='fallos_consecutivos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fallos seguidos'),
        ),
    ]
