# Generated by Django 5.0.1 on 2026-05-02 19:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MX', verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tipo_cliente', models.CharField(choices=[('nuevo', 'Nuevo'), ('frecuente', 'Frecuente'), ('inactivo', 'Inactivo')], default='nuevo', max_length=20, verbose_name='Tipo de cliente')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre el cliente', verbose_name='Notas')),
                ('total_citas', models.IntegerField(default=0, verbose_name='Total de citas')),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total gastado')),
                ('ultima_visita', models.DateTimeField(blank=True, null=True, verbose_name='Última visita')),
                ('creado_manualmente', models.BooleanField(default=False, help_text='Si fue creado por el administrador o automáticamente por el sistema', verbose_name='Creado manualmente')),
                ('acepta_whatsapp', models.BooleanField(default=True, verbose_name='Acepta WhatsApp')),
                ('acepta_sms', models.BooleanField(default=True, verbose_name='Acepta SMS')),
                ('acepta_email', models.BooleanField(default=True, verbose_name='Acepta Email')),
                ('acepta_promociones', models.BooleanField(default=True, verbose_name='Acepta promociones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-ultima_visita', '-fecha_registro'],
                'indexes': [models.Index(fields=['telefono'], name='clientes_cl_telefon_6177bc_idx'), models.Index(fields=['tipo_cliente'], name='clientes_cl_tipo_cl_cae2d6_idx'), models.Index(fields=['ultima_visita'], name='clientes_cl_ultima__fa445a_idx')],
                'unique_together': {('negocio', 'telefono')},
            },
        ),
    ]
