# Generated by Django 5.0.1 on 2026-06-18 01:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-ultima_visita', '-fecha_registro'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='CO', verbose_name='Teléfono'),
        ),
    ]
