# Generated by Django 5.0.1 on 2026-06-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_ciudad_cliente_codigo_postal_and_more'),
        ('negocios', '0003_negocio_es_a_domicilio'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['negocio', 'telefono'], name='clientes_cl_negocio_dcd8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['negocio', 'tipo_cliente', '-ultima_visita'], name='clientes_cl_negocio_ef54a8_idx'),
        ),
    ]
