# Generated by Django 5.0.1 on 2026-10-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_clientes_cl_negocio_dcd8fa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='no_exigir_abono',
            field=models.BooleanField(default=False, help_text='Sus citas quedan confirmadas sin pedir anticipo, aunque el servicio lo requiera', verbose_name='No exigir abono'),
        ),
    ]
