# Generated by Django 5.0.1 on 2026-10-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_no_exigir_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_baja',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo de baja'),
        ),
    ]
