# Generated by Django 5.0.1 on 2026-05-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la promoción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('mensaje', models.TextField(help_text='Mensaje que recibirán los clientes', verbose_name='Mensaje a enviar')),
                ('segmento', models.CharField(choices=[('todos', 'Todos los clientes'), ('nuevos', 'Clientes nuevos'), ('frecuentes', 'Clientes frecuentes'), ('inactivos', 'Clientes inactivos'), ('personalizado', 'Segmento personalizado')], default='todos', max_length=20, verbose_name='Segmento de clientes')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promociones/', verbose_name='Imagen')),
                ('codigo_descuento', models.CharField(blank=True, max_length=50, verbose_name='Código de descuento')),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de descuento')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('programada', 'Programada'), ('enviada', 'Enviada'), ('finalizada', 'Finalizada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('total_destinatarios', models.IntegerField(default=0, verbose_name='Total de destinatarios')),
                ('total_enviados', models.IntegerField(default=0, verbose_name='Total enviados')),
                ('total_fallidos', models.IntegerField(default=0, verbose_name='Total fallidos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
