# Generated by Django 5.0.1 on 2026-05-02 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('duracion_minutos', models.IntegerField(help_text='Duración estimada del servicio en minutos', verbose_name='Duración (minutos)')),
                ('frecuencia_dias', models.IntegerField(blank=True, help_text='Cada cuántos días se recomienda repetir este servicio (ej: 30 días para corte de cabello)', null=True, verbose_name='Frecuencia sugerida (días)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen del servicio')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('requiere_abono', models.BooleanField(default=False, help_text='Si está marcado, sobrescribe la configuración general del negocio', verbose_name='Requiere abono específico')),
                ('monto_abono', models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo de abono para este servicio', max_digits=10, null=True, verbose_name='Monto de abono')),
                ('porcentaje_abono', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje del precio como abono', max_digits=5, null=True, verbose_name='Porcentaje de abono (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['negocio', 'orden', 'nombre'],
                'unique_together': {('negocio', 'nombre')},
            },
        ),
    ]
