# Generated by Django 5.0.1 on 2026-06-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='requiere_contacto_directo',
            field=models.BooleanField(default=False, help_text='Marcar si este servicio requiere contactar directamente para coordinar (ej: servicios a domicilio que dependen de distancia y disponibilidad)', verbose_name='Requiere coordinación directa'),
        ),
    ]
