# Generated by Django 5.0.1 on 2026-05-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del abono')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='transferencia', max_length=20, verbose_name='Método de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('numero_referencia', models.CharField(blank=True, help_text='Número de referencia de la transferencia', max_length=100, verbose_name='Número de referencia')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='abonos/comprobantes/', verbose_name='Comprobante de pago')),
                ('fecha_limite', models.DateTimeField(verbose_name='Fecha límite de pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
