# Generated by Django 5.0.1 on 2026-05-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonos', '0001_initial'),
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abono', to='citas.cita', verbose_name='Cita'),
        ),
        migrations.AddField(
            model_name='abono',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
    ]
