# Generated by Django 5.0.1 on 2026-10-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido'), ('exonerado', 'Exonerado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
