# Generated by Django 5.0.1 on 2026-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonos', '0003_estado_exonerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que el dueño confirmó haber recibido (puede ser más que el abono exigido)', max_digits=10, null=True, verbose_name='Monto recibido'),
        ),
        migrations.AddField(
            model_name='abono',
            name='monto_reportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto reportado por el cliente'),
        ),
    ]
