# Generated by Django 5.0.1 on 2026-09-04 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0004_onboardingprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('trial', 'Trial Gratuito'), ('mensual', 'Mensual')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_dias', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('max_citas_mes', models.IntegerField(blank=True, null=True)),
                ('max_servicios', models.IntegerField(blank=True, null=True)),
                ('max_clientes', models.IntegerField(blank=True, null=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('soporte_prioritario', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('meses_gratis', models.IntegerField(default=1, editable=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('negocio_asignado', models.ForeignKey(blank=True, help_text='Si se asigna, solo este negocio puede usarlo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones_asignados', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='RegistroNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente_email', 'Pendiente Validación Email'), ('completado', 'Registro Completado'), ('expirado', 'Expirado')], default='pendiente_email', max_length=20)),
                ('token_validacion', models.CharField(db_index=True, max_length=100, unique=True)),
                ('fecha_token_expira', models.DateTimeField()),
                ('email_validado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Registro de Negocio',
                'verbose_name_plural': 'Registros de Negocios',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('trial', 'Trial Activo'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('suspendida', 'Suspendida')], default='trial', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('token_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_renovacion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='negocios.negocio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.plansuscripcion')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], max_length=20)),
                ('pasarela', models.CharField(max_length=50)),
                ('transaccion_id', models.CharField(max_length=255, unique=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripciones.suscripcion')),
            ],
            options={
                'verbose_name': 'Pago de Suscripción',
                'verbose_name_plural': 'Pagos de Suscripción',
            },
        ),
        migrations.CreateModel(
            name='UsoCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('meses_extendidos', models.IntegerField(default=1)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='suscripciones.cupon')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Uso de Cupón',
                'verbose_name_plural': 'Usos de Cupones',
                'unique_together': {('cupon', 'negocio')},
            },
        ),
    ]
