# Generated by Django 5.0.1 on 2026-09-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_onboardingprogress'),
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaReferidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='True si tiene los 3 referidos activos')),
                ('fecha_ultimo_cupon', models.DateTimeField(blank=True, help_text='Última vez que se generó un cupón', null=True)),
                ('total_cupones_generados', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programa_referidos', to='negocios.negocio')),
                ('negocio_referido_1', models.ForeignKey(blank=True, help_text='Primer negocio referido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referido_por_slot_1', to='negocios.negocio')),
                ('negocio_referido_2', models.ForeignKey(blank=True, help_text='Segundo negocio referido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referido_por_slot_2', to='negocios.negocio')),
                ('negocio_referido_3', models.ForeignKey(blank=True, help_text='Tercer negocio referido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referido_por_slot_3', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Programa de Referidos',
                'verbose_name_plural': 'Programas de Referidos',
            },
        ),
    ]
