# Generated by Django 5.0.1 on 2026-10-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_programareferidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronegocio',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registronegocio',
            name='telefono',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
