# Generated by Django 5.0.1 on 2026-05-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del negocio')),
                ('tipo', models.CharField(choices=[('spa', 'Spa'), ('peluqueria', 'Peluquería'), ('barberia', 'Barbería'), ('salon_belleza', 'Salón de Belleza'), ('otro', 'Otro')], default='spa', max_length=20, verbose_name='Tipo de negocio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL única')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('horario_apertura', models.TimeField(blank=True, null=True, verbose_name='Hora de apertura')),
                ('horario_cierre', models.TimeField(blank=True, null=True, verbose_name='Hora de cierre')),
                ('dias_atencion', models.CharField(default='Lunes a Viernes', help_text='Ejemplo: Lunes a Viernes, Lunes a Sábado', max_length=200, verbose_name='Días de atención')),
                ('requiere_abono', models.BooleanField(default=False, verbose_name='Requiere abono')),
                ('porcentaje_abono', models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje del servicio que se requiere como abono', max_digits=5, verbose_name='Porcentaje de abono (%)')),
                ('monto_abono_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Si se define, se usa este monto en lugar del porcentaje', max_digits=10, null=True, verbose_name='Monto fijo de abono')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, verbose_name='Número de cuenta')),
                ('clabe', models.CharField(blank=True, max_length=18, verbose_name='CLABE interbancaria')),
                ('titular_cuenta', models.CharField(blank=True, max_length=200, verbose_name='Titular de la cuenta')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocios/logos/', verbose_name='Logo')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='negocios/portadas/', verbose_name='Imagen de portada')),
                ('color_primario', models.CharField(default='#007bff', max_length=7, verbose_name='Color primario')),
                ('color_secundario', models.CharField(default='#6c757d', max_length=7, verbose_name='Color secundario')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('acepta_reservas_online', models.BooleanField(default=True, verbose_name='Acepta reservas online')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('administrador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='negocio', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha y hora de fin')),
                ('motivo_interno', models.CharField(help_text='Este motivo solo lo ve el administrador', max_length=200, verbose_name='Motivo interno')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Bloqueo de agenda',
                'verbose_name_plural': 'Bloqueos de agenda',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('esta_abierto', models.BooleanField(default=True, verbose_name='Está abierto')),
                ('hora_apertura', models.TimeField(verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de cierre')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_horario', to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Configuración de horario',
                'verbose_name_plural': 'Configuraciones de horario',
                'ordering': ['dia_semana'],
                'unique_together': {('negocio', 'dia_semana')},
            },
        ),
    ]
