# Generated by Django 5.0.1 on 2026-06-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='clabe',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de cuenta bancaria'),
        ),
    ]
