# Generated by Django 5.0.1 on 2026-06-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_alter_negocio_clabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='es_a_domicilio',
            field=models.BooleanField(default=False, help_text='Marcar si el negocio ofrece servicios a domicilio (sin local fijo)', verbose_name='Servicio a domicilio'),
        ),
    ]
