# Generated by Django 5.0.1 on 2026-08-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_negocio_es_a_domicilio'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_completado', models.IntegerField(default=0)),
                ('datos_basicos_completado', models.BooleanField(default=False)),
                ('datos_basicos_fecha', models.DateTimeField(blank=True, null=True)),
                ('identidad_visual_completado', models.BooleanField(default=False)),
                ('identidad_visual_fecha', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_contacto_completado', models.BooleanField(default=False)),
                ('ubicacion_contacto_fecha', models.DateTimeField(blank=True, null=True)),
                ('horarios_completado', models.BooleanField(default=False)),
                ('horarios_fecha', models.DateTimeField(blank=True, null=True)),
                ('servicios_completado', models.BooleanField(default=False)),
                ('servicios_fecha', models.DateTimeField(blank=True, null=True)),
                ('onboarding_finalizado', models.BooleanField(default=False)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('onboarding_saltado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Progreso de Onboarding',
                'verbose_name_plural': 'Progresos de Onboarding',
            },
        ),
    ]
