# Generated by Django 5.0.1 on 2026-10-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_onboardingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='daviplata',
            field=models.CharField(blank=True, help_text='Número de celular de Daviplata', max_length=20, verbose_name='Daviplata'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='llave_breb',
            field=models.CharField(blank=True, help_text='Tu llave para pagos inmediatos (celular, cédula, correo o alfanumérica)', max_length=100, verbose_name='Llave Bre-B'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='nequi',
            field=models.CharField(blank=True, help_text='Número de celular de Nequi', max_length=20, verbose_name='Nequi'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='qr_pago',
            field=models.ImageField(blank=True, help_text='Imagen del QR de tu banco o billetera para que el cliente escanee y pague', null=True, upload_to='negocios/qr_pago/', verbose_name='Código QR de pago'),
        ),
    ]
