# Generated by Django 5.0.1 on 2026-06-30 02:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de solicitud')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['token', 'usado'], name='authenticat_token_33d6fb_idx'), models.Index(fields=['usuario', '-fecha_creacion'], name='authenticat_usuario_a57ed5_idx')],
            },
        ),
    ]
