# Generated by Django 5.0.1 on 2026-10-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_tokenrecuperacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Teléfono'),
        ),
    ]
